spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wangyaochong
    password: qwerqwer
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learnmybatisspringboot.generated.entity
debug: true
