hikari:
  read:
    jdbc-url: jdbc:mysql://www.wangyaochong.com:3306/read?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: wangyaochong
    password: qwer@Qwer
    maximum-pool-size: 80
    pool-name: read
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  write:
    jdbc-url: jdbc:mysql://www.wangyaochong.com:3306/write?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: wangyaochong
    password: qwer@Qwer
    maximum-pool-size: 80
    pool-name: write
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
